apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: nicholasdille/pacman:latest
          ports:
            - containerPort: 8080
